### ISSUE TITLE
Add Note mutation

### ISSUE THREAD

**Issue by talyguryn** [codex-team/electon.editor#110]
Send Notes mutation to the Cloud.

See example of Folders Mutations: https://github.com/codex-team/codex.notes/pull/113

**Comment by neSpecc** [comment]
Where to include `sync` event: 
https://github.com/codex-team/codex.notes/blob/version2.0/src/models/note.js#L161

Note Mutation description: 
https://github.com/codex-team/codex.notes.server/blob/master/www/schema/types/Mutation.php#L104
