### ISSUE TITLE
Auth errors exceptions handling

### ISSUE THREAD

**Issue by neSpecc** [codex-team/electon.editor#116]
- При неверных данных авторизации, на сервере в контроллере OAuth.php в проверке `if (!is_null($profileInfo->error)) {` логгируется `$profileInfo->error->message`,  при этом пользователь видит белый экран.

<img width="1197" alt="screen shot 2018-01-16 at 21 17 42" src="https://user-images.githubusercontent.com/3684889/35004912-be87d3cc-fb02-11e7-8771-8492e4fd1f1b.png">

**Comment by neSpecc** [comment]
чтобы воспроизвести, можно подставить на сервере в `.env` некорректный `client_id`

**Comment by talyguryn** [comment]
closed in codex-team/codex.notes.server#49
