### ISSUE TITLE
Close Folder settings panel, when move to the Root Folder

### ISSUE THREAD

**Issue by gohabereg** [codex-team/electon.editor#137]
### Expected behaviour

1. Open Folder
2. Open Folder settings
3. Move to the Root Folder (by left swipe for example)
4. Open another Folder

I expected that I would see Notes list of another Folder.

### Actual behaviour

I saw was that first Folder settings panel was opened instead.

### Steps to reproduce

1. Open Folder
2. Open Folder settings
3. Move to the Root Folder (by left swipe for example)
4. Open another Folder

### App version

I use CodeX Notes [v2.0].

**Comment by actorFromCalifornia** [comment]
Close #137
