### ISSUE TITLE
Queries authorization

### ISSUE THREAD

**Issue by neSpecc** [codex-team/electon.editor#99]
1. `client` After client-auth , request API server with the User mutation.
2. `API` Add new User in DB 
3. `API` Generate JWT with authorisation data on the API server and return it to the Client
4. `client` Save JWT somewhere on the client-side 
5. `client` Pass JWT with all GraphQL queries
6. `API` Check JWT in the middleware

**Comment by gohabereg** [comment]
closed by #103
